name: CVE Scan
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: read

jobs:
  security_audit:
    runs-on: ubuntu-latest
    steps:
        - uses: golang/govulncheck-action@v1
          with:
            go-version-input: 'stable'
            check-latest: true
  
